import { Nav, NavLink } from "@/components/Nav";
import { Metadata } from "next";
export const dynamic = "force-dynamic";
import React from "react";
export const metadata: Metadata = {
  title: "Store Page",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav>
        <NavLink href={"/"}>Home</NavLink>
        <NavLink href={"/products"}>Products</NavLink>
        <NavLink href={"/orders"}>My Orders</NavLink>
      </Nav>
      <div className="container my-6 mx-5">{children}</div>
    </>
  );
}
