import { Nav, NavLink } from "@/components/Nav";
import { Metadata } from "next";
export const dynamic = "force-dynamic"
import React from "react";
export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav>
        <NavLink href={"/admin"}>Dashboard</NavLink>
        <NavLink href={"/admin/products"}>Products</NavLink>
        <NavLink href={"/admin/users"}>Customers</NavLink>
        <NavLink href={"/admin/orders"}>Orders</NavLink>
      </Nav>
      <div className="container my-6 mx-5">{children}</div>
    </>
  );
}
